### ISSUE TITLE
chunked_midi  generation bash file

### ISSUE THREAD

**Issue by ben2002chou** [lukewys/chamber-ensemble-generator#3]
can the authors provide the chunked_midi  generation bash file mentioned in https://github.com/lukewys/chamber-ensemble-generator/blob/master/data_pipeline.md? How much faster is chunked generation?

**Comment by lukewys** [comment]
Hi, chunked generation bash is basically multiple bash files, each generating a subset of data. (https://github.com/lukewys/chamber-ensemble-generator/blob/master/create_cocochorales.sh) You can group the MIDI files generated in step 1 into subfolders and generate for each subfolder for a job and so on. My chunked midi generation script contains cluster-specific codes which I think might not be most helpful. If you are familiar with bash script I believe you can easily create your own version.

As of speed, I think I had approximately 256 jobs and each job has 4 CPU cores. The total time is approximately 18-24 hours, but defiantly less than 24 hours to generate the whole thing.

**Comment by ben2002chou** [comment]
Thank you for the response, and thank you for this great work, this is very helpful! is there any reason for the choice of 4 CPU cores per job, with 16GB ram? From my understanding the entire process uses CPU only, and I would like to understand why this configuration was the choice.

**Comment by lukewys** [comment]
Because the main time bottleneck of MIDI-DDSP is the autoregressive
generation of f0 by RNN in the synthesis generator. This process uses only
1 CPU (because is it basically a for loop where each step just runs a very
small model). So I allocate 4 CPU just to not waste other idle CPU cores. I
think if you run multiple bash scripts in the same machine or virtual
instance, it would be even more efficient, I would imagine.

Ben Chou ***@***.***> 于2024年2月23日周五 12:38写道：

**Comment by ben2002chou** [comment]
Thanks very much! I will mark this issue closed.
